// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCknOsahXpSOnbFTHcI1v2D9dseXmoli_M',
    appId: '1:990846190649:web:ccf1807726e365cbd3f9e8',
    messagingSenderId: '990846190649',
    projectId: 'flutterkidsauth',
    authDomain: 'flutterkidsauth.firebaseapp.com',
    storageBucket: 'flutterkidsauth.appspot.com',
    measurementId: 'G-J8WWB4CR53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABy_3wcA23tHsZWwqPoHSrcNoVKPpQQe0',
    appId: '1:990846190649:android:909678e742cfb937d3f9e8',
    messagingSenderId: '990846190649',
    projectId: 'flutterkidsauth',
    storageBucket: 'flutterkidsauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTEE0iKDwmG0H274EFByv8XScN8ugg8xg',
    appId: '1:990846190649:ios:b6a52dd20a532bb9d3f9e8',
    messagingSenderId: '990846190649',
    projectId: 'flutterkidsauth',
    storageBucket: 'flutterkidsauth.appspot.com',
    iosBundleId: 'com.example.childAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTEE0iKDwmG0H274EFByv8XScN8ugg8xg',
    appId: '1:990846190649:ios:b6a52dd20a532bb9d3f9e8',
    messagingSenderId: '990846190649',
    projectId: 'flutterkidsauth',
    storageBucket: 'flutterkidsauth.appspot.com',
    iosBundleId: 'com.example.childAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCknOsahXpSOnbFTHcI1v2D9dseXmoli_M',
    appId: '1:990846190649:web:4177f596aebbe804d3f9e8',
    messagingSenderId: '990846190649',
    projectId: 'flutterkidsauth',
    authDomain: 'flutterkidsauth.firebaseapp.com',
    storageBucket: 'flutterkidsauth.appspot.com',
    measurementId: 'G-VQXCQP4GXY',
  );
}
